# Generated by Django 4.2.5 on 2023-09-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('published_at', models.DateField()),
            ],
        ),
    ]
