# Generated by Django 4.2.5 on 2023-09-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='published_at',
        ),
    ]
