# Generated by Django 4.2.5 on 2023-09-13 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_remove_note_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='create_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
