# Generated by Django 4.2.5 on 2023-09-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_note_create_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='create_add',
        ),
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
